### ISSUE TITLE
En tant qu'opérateur, je transmets le projet à un autre opérateur

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#100]
Lorsqu'un opérateur A mets en relation le demandeur avec un autre opérateur B, l'opérateur A n'a plus accès au projet (à préciser).

**Comment by annemarie35** [comment]
@krichtof @philcassagne 
La fonctionnalité actuelle est : une fois que le demandeur a choisi son opérateur, les autres opérateurs invités n'ont plus accès au projet.
Il manque une fonctionnalité qui permet à un opérateur de ne plus accompagner un projet :
- annuler le choix du demandeur ?
- envoyer une invitation à un autre opérateur puis attendre que le demandeur valide.
