### ISSUE TITLE
Créer les tables de référence opal

### ISSUE THREAD

**Issue by krichtof** [sgmap/mpal#102]
Pour créer un dossier dans opal, il convient au préalable de créer les tables de référence pour utiliser les bons id pour certains attributs nécessaires à la création d'un dossier.

A partir du fichier TableReference, il s'agit de créer les tables suivantes :
- qdm (qualité du demandeur)
- cat (catégorie du demandeur)
- ntr (nature des travaux)

**Comment by yaf** [comment]
[TableReferencev0.2.txt](https://github.com/sgmap/mpal/files/481139/TableReferencev0.2.txt)

**Comment by yaf** [comment]
Je supose que c'est `cad` et non `cat` ?
