### ISSUE TITLE
En tant que demandeur, je choisis mon opérateur

### ISSUE THREAD

**Issue by krichtof** [sgmap/mpal#104]
Une fois avoir demandé des informations à un opérateur, le demandeur peut choisir d'être accompagné par un opérateur.
- [x] Le projet passe alors de l'état "prospect" à l'état "en cours".
- [x] Dans la page Intervenants, on voit uniquement l'opérateur choisi. On ne voit plus les intervenants disponibles, ni ceux invités.
- [x] Les autres opérateurs invités à consulter le projet ne peuvent plus y accéder. Seul l'opérateur choisi peut y accéder.
- [ ] Envoi d'un mail à l'opérateur

**Comment by annemarie35** [comment]
Manque que le mail et on est bon :)

**Comment by annemarie35** [comment]
Création de l'issue #144 pour finir.
