### ISSUE TITLE
Affiche la ou les thématiques dans le tableau de bord

### ISSUE THREAD

**Issue by krichtof** [sgmap/mpal#115]
Déduit du plan travaux de la demande, uniquement lorsqu'une des cases "retenu" de la thématique est cochée.
- Faut-il prendre en compte les thématiques lorsqu'une des cases souhaité ou préconisé est cochée ?
- dans le plan travaux n'apparait rien sur la thématique "travaux lourds", "insalubrité"

**Comment by krichtof** [comment]
La ou les thématiques sont déduites du plan de travaux (et uniquement des travaux retenus) et des éléments de diagnostic.
En attente de la règle pour l'implémenter.

**Comment by krichtof** [comment]
voici comment sont calculées par l'Anah les priorités en terme de logements dans le tableau de bord

Les "logements indignes" sont les logements qui : 

qui font l'objet soit d'un arrêté d'insalubrité, ou un arrêté de péril, ou iune nsalubrité avérée par une grille d'insalubrité avec un coefficient d'insalubrité >= 0.3 * 

ou alors qui font l'objet d'une procédure au titre de l'art. 129.1 (équ. Communs) ou de l'art. 1334.2 (risque sat.) ou de l'art. 1334.5 (CREP)

(*si  le coefficient est supérieur ou égal  à 0.4 c'est un logement indigne  mais un logement dont le coefficient est compris entre 0.3 et 0.4 après avis de la CLAH le dossier peut éventuellement être considéré comme entrant dans les logements indignes et donc bénéficier des procédures SSH ou TRAVAUX LOURDS taux et plafonds majorés si nécessaire)

Les logements indIgnes peuvent bénéficier soit de la procédure TRAVAUX LOURDS soit de la procédure TRAVAUX SSH

les  "logements très dégradés" sont les logements qui font l'objet d'une grille de dégradation pour laquelle l'indicateur de dégradation est >= 0.55

Les logements très dégradés ne peuvent bénéficier que de la procédure TRAVAUX LOURDS
les logements autonomie sont les logements pour lesquels un niveau  GIR  ou un justificatif handicap a été renseigné.
Nota : On comptabilise au titre de l'autonomie que les logements non comptés antérieurement : qui ne sont ni indignes, ni très dégradés
Les logements "Energie" : 
On comptabilise sur cette ligne les logements ayant un gain énergétique ≥ 25%, à condition de ne pas être déjà
comptabilisés en "logement indigne" ni en "très dégradé", ni en "autonomie".

**Comment by annemarie35** [comment]
Cf issue #88
