### ISSUE TITLE
Visualise une demande synthétique

### ISSUE THREAD

**Issue by krichtof** [sgmap/mpal#117]
Pour un instructeur et un demandeur

**Comment by annemarie35** [comment]
@krichtof Pourrais tu préciser cette issue avec quelques éléments s'il te plaît ?

**Comment by krichtof** [comment]
Actuellement, l'instructeur voit la demande de la même manière qu'un opérateur, à savoir, la description du projet avec tous les travaux possibles.
On doit lui présenter la demande avec uniquement les travaux sélectionnés (préconisé, souhaité, retenu) et non l'ensemble des travaux possibles.
Le demandeur doit avoir également accès à cette page demande "synthétique"

**Comment by annemarie35** [comment]
visualise la recap de la demande
