### ISSUE TITLE
Cache l'accès à la page demande si l'opérateur n'est pas encore choisi

### ISSUE THREAD

**Issue by krichtof** [sgmap/mpal#121]

**Comment by yaf** [comment]
En tant que quoi ? Qui ? Comment ? D'où ? :-)

**Comment by krichtof** [comment]
Personne (demandeur, pris, instructeur, operateur) n'a accès à la page opérateur si le l'opérateur n'est pas encore choisi (dit autrement, si le projet a comme statut prospect) ;)
