### ISSUE TITLE
Ajoute le diagnostic du logement

### ISSUE THREAD

**Issue by krichtof** [sgmap/mpal#124]
Voir fiche google drive

**Comment by krichtof** [comment]
Ventilation inadaptée : champ obligatoire
Présence de traces d'humidité : champ obligatoire
Note degradation et insalubrité : valeur entre 0 et 1

**Comment by annemarie35** [comment]
Je manque d'informations là dessus @krichtof

**Comment by krichtof** [comment]
L'idée est d'ajouter les 3 champs précisés ci-dessus dans la section diagnostic de la page demande.
