### ISSUE TITLE
Informer l'utilisateur des conditions générales utilisateur

### ISSUE THREAD

**Issue by krichtof** [sgmap/mpal#142]

**Comment by annemarie35** [comment]
Ajouter une case à cocher pour l'utilisateur dès la page d'accueil, au moment où l'opérateur renseigne son numéro fiscal.

**Comment by annemarie35** [comment]
La page existe et un lien est disponible depuis le menu bas

**Comment by annemarie35** [comment]
Suite à l'atelier wording, de nouvelles cases à cocher ont été proposées, du coup se pose la question du stockage.
Nouvelle table ou nouveaux champs dans la table projet @krichtof ?
