### ISSUE TITLE
Permet au demandeur de faire sa demande en décrivant plus précisement son projet

### ISSUE THREAD

**Issue by annemarie35** [sgmap/mpal#162]
Nouvel écran Nature du besoin et du projet, avec champs libre et questions telles que 

**« Quelles difficultés rencontrez-vous dans votre logement?**

- j’ai froid, mon logement est mal isolé
- je veux réaliser des économies d’énergies 
- j’ai du mal à me déplacer 
- un des occupants est handicapé
- mon logement est globalement en mauvais état 
- Autres : champ libre complémentaire

**et/ou Quels travaux souhaitez-vous effectuer ?**
- changer mon système de chauffage
- isoler mon logement
- adapter ma salle de bain
- rendre plus accessible mon logement
- réaliser d’importants travaux (plusieurs des éléments ci-dessus et ou d’autres)
- Autres : champ libre complémentaire

![img_1466](https://cloud.githubusercontent.com/assets/7688741/20007050/cdb3fc34-a29a-11e6-9388-3b0a35445f86.JPG)

**Comment by annemarie35** [comment]
-> rajouter une validation sur "au moins une case cochée ou au moins une case champ libre remplie"

**Comment by annemarie35** [comment]
-> ne pas faire l'update si tous les params sont nil

**Comment by krichtof** [comment]
Fait : https://github.com/sgmap/mpal/commit/163f05856fd3ea9ccd9ac756e0ff82cd00d58bc9
