### ISSUE TITLE
Bug lien opérateur

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#183]
le lien reçu par l'opérateur lorsqu'il a été choisi par le demandeur renvoie à la page d'accueil avec le message : Vous n'avez pas accès à cette page

En tant qu'opérateur, je devrais pouvoir accéder au dossier.

**Comment by annemarie35** [comment]
Je n'ai pas réussi à reproduire le bug. 
Cela peut arriver si le projet est supprimé, les mails n'étant pas supprimé automatiquement. 
Dans ce cas, si on clique sur le lien, on arrive sur un projet qui n'existe plus, d'où erreur.
C'est une piste.

**Comment by philcassagne** [comment]
Je suis parti d'un nouveau dossier.
Je refais un test.
Il s'agit du deuxième mail reçu par l'opérateur, quand il est choisi par le demandeur.

**Comment by annemarie35** [comment]
ah ok, c'est ce bug alors #157

**Comment by annemarie35** [comment]
Bug corrigé
