### ISSUE TITLE
En tant qu'agent, je consulte les projets que j'accompagne

### ISSUE THREAD

**Issue by annemarie35** [sgmap/mpal#22]

**Comment by krichtof** [comment]
Si je suis un agent opérateur, je vois la liste des projets de l'opérateur auquel je fais partie.
Si je suis un agent instructeur, je vois la liste des projets de la ddt auquelle je fais partie.

**Comment by krichtof** [comment]
- [ ] Associer un agent (une personne) à un intervenant (la structure qui l'emploie)
- [ ] Lister les projets d'un intervenant (structure)

**Comment by krichtof** [comment]
Dupliqué avec #90
