### ISSUE TITLE
En tant qu'agent/conseiller, j'évalue l'éligibilité du demandeur

### ISSUE THREAD

**Issue by annemarie35** [sgmap/mpal#25]

**Comment by annemarie35** [comment]
Actuellement, l'intervenant peut voir si le plafond de ressources est dépassé ou pas.
@philcassagne est-ce qu'on peut fermer cette issue ?

**Comment by philcassagne** [comment]
Bonjour Anne-Marie,

Merci pour le travail réalisé.
Je suis encore un peu en vacances. Aussi je propose de faire un point 
demain sur les issues.

Est ce que tout le monde est disponible pour se retrouver demain à 9h30 
à Sully?

Cordialement,

Philippe Cassagne



Le 23/08/2016 11:02, > Anne-Marie (par Internet, dépôt 
noreply@github.com) a écrit :
