### ISSUE TITLE
En tant qu'instructeur Anah, je m'affecte un projet dans Opal

### ISSUE THREAD

**Issue by annemarie35** [sgmap/mpal#37]
A partir de la liste des projets qui ne sont pas encore en cours d'instruction (et donc pas créés dans Opal), un agent instructeur peut s'affecter un projet. 
Lorsqu'il clique sur un projet qui n'est pas encore affecté, il arrive sur le projet en question. Il peut ensuite s'affecter le projet, ce qui créera le projet dans Opal

**Comment by annemarie35** [comment]
@philcassagne je ne suis pas sure que ce soit l'instructeur de l'Anah qui effectue l'opération, le vocabulaire de cette issue est à discuter je pense

**Comment by krichtof** [comment]
- [ ] Ajouter le bouton "Je m'affecte ce projet dans OPAL" (uniquement visible pour un agent instructeur) et faire une requête qui renvoie une erreur
- [ ] Constituer les tables de référence 
- [ ] Créer le dossier dans OPAL lorsqu'un agent instructeur clique sur le bouton

**Comment by philcassagne** [comment]
Anne-Marie a raison de dire que c'est l'opérateur qui s'affecte le projet et non l'instructeur. 
Encore que ce cas soit maintenant géré par le fait que l'opérateur peut devenir le référent du dossier sur action du demandeur (parfois accompagné par l'opérateur).
En revanche on a bien "en tant qu'instructeur je transfère le dossier dans OPAL depuis le tableau de bord des dossiers qui sont à l'état "Transmis au service instructeur" ".
Le bouton "transférer à OPAL" peut être dans le projet et dans le tableau de bord.

**Comment by annemarie35** [comment]
Je ne peux m'affecter un projet que si je réponds aux conditions suivantes :
- je suis connecté en tant qu'instructeur
- le statut du projet vaut "Transmis aux services instructeurs"
