### ISSUE TITLE
[Bug] Un intervenant ne doit pas modifier la liste des occupants

### ISSUE THREAD

**Issue by annemarie35** [sgmap/mpal#45]
Actuellement, dans la vue projet / intervenant, l'intervenant peut modifier la liste des occupants.

**Comment by annemarie35** [comment]
A discuter dans l'usage ? @krichtof

**Comment by annemarie35** [comment]
Je fais remonter l'issue car la question se pose toujours. 
L' opérateur peut-il modifier les données du demandeur ? (Actuellement, seul le demandeur voit les boutons pour modifier les données du projet)
@philcassagne

**Comment by philcassagne** [comment]
Merci pour ce rappel. C'est une excellente question à poser au prochain Open Lab.
