### ISSUE TITLE
Le département extrait de l'API BAN est faux pour certaines communes

### ISSUE THREAD

**Issue by kemenaran** [sgmap/mpal#491]
Salut 👋 

Dans `services/api_ban.rb`, le code de l'app récupère le département en considérant que ce sont les deux premiers caractères du code postal.
https://github.com/sgmap/mpal/blob/26534563c9bd8935401c644a0bbe2e80108137f0/app/services/api_ban.rb#L19

En fait il s'avère que ça ne fonctionne pas : il y a des communes dont le code postal n'est pas dans le département de la commune 😱 ([liste de ces communes et explication](https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_dont_le_code_postal_ne_correspond_pas_au_d%C3%A9partement))

Résultat : certains demandeurs vont se voir assignés au mauvais département.

Suggestion : apparemment les deux premiers caractères du **Code Insee** correspondent eux toujours au département. Le code pourrait donc faire :

```ruby
departement = code_insee[0,2]
```

Mais il faudrait vérifier que je ne dis pas de bêtise (et que toutes les adresses renvoyées par la BAN ont bien un code INSEE).

**Comment by jvignolles** [comment]
Salut Pierre !
Je remonte l’information.
Merci du pointeur ! 😮
