### ISSUE TITLE
Je ne peux plus me connecter en tant que demandeur si je viens d'accéder à un projet via une invitation

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#51]
En tant que demandeur, sur un projet existant, lorsque je me logue en tant 88 / 1588, j'arrive sur l'espace opérateur au lieu de mon espace demandeur

**Comment by annemarie35** [comment]
Si on se connecte en tant qu'opérateur à partir du lien reçu (et du token) qui est fournit, on ne peut plus se connecter en tant que demandeur.

**Comment by annemarie35** [comment]
Et autre chose, une fois qu'on s'est connecté en tant que par exemple DDT 25 suite à une invitation, si je clique sur une invitation envoyée à un autre intervenant, je reste connecté en tant que DDT 25.
Je peux voir aussi n'importe quel projet.
Ex http://localhost:5000/projets/3/demande
http://localhost:5000/projets/1/demande
Et ce, même si je n'ai pas été invité à prendre connaissance du projet.

**Comment by annemarie35** [comment]
Done via 01c5c89a2448e63f614b21fedb18243989ab84b4  mais non fermé car bug "invalid authenticity token" après expiration de la session.

**Comment by krichtof** [comment]
Je n'ai pas réussi à reproduire ce problème. On pourra réouvrir si besoin
