### ISSUE TITLE
En tant que demandeur, à la création d'un nouveau projet, je devrais voir le PRIS

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#52]
En tant que demandeur, à la création d'un nouveau projet, je devrais voir le PRIS. Ceci avait été développé. Mais aujourd'hui le PRIS n'est plus visible, lorsque je me connecte avec 88 / 1588. On voit seulement les opérateurs. Sans doute parce qu'il s'est avéré nécessaire de by-passer les PRIS. Je propose d'afficher le PRIS et les opérateurs au demandeur. Pour qu'il puisse avoir le choix de passer par le PRIS ou directement prendre contact avec un opérateur.

**Comment by annemarie35** [comment]
Done. Voir issue #53
