### ISSUE TITLE
PRIS des départements - Plusieurs PRIS pour un même département

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#53]
En tant que demandeur du 95, je dois voir l'ADIL 95. Pareil pour le 25 et ADIL 25. 
A noter qu'il existe des départements comme le 31 (et je crois aussi le 14) où il y a plusieurs PRIS.
Je vais en fournir la liste pour le 31 (et le 14 éventuellement)

**Comment by annemarie35** [comment]
Les pris sont de nouveaux affichés. Ils peuvent être invités tout comme un opérateur.
Par contre, comment disparaissent-ils de la page demandeur ? 
Actuellement ce n'est pas le cas, je les ai laissé.
C'est à prévoir et à discuter, est-ce lors d'une action du demandeur ? 
Restent-ils visibles ailleurs ?
