### ISSUE TITLE
Upload csv plan de travaux

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#54]
En tant qu'opérateur, lorsque j'upload le fichier travaux.csv, je reçois l'erreur 
CSV::MalformedCSVError in TransfertCsvController#create

**Comment by krichtof** [comment]
Peux-tu joindre le fichier csv que tu as utilisé pour l'upload ?
Je viens de faire le test avec le fichier csv dans mentionné dans le wiki (https://raw.githubusercontent.com/sgmap/mpal/dev/docs-api/travaux.csv) et je n'ai pas d'erreur.

**Comment by annemarie35** [comment]
Alors, quand je vais sur http://anah-demo.beta.gouv.fr/projets/76/demande et que j'uploade le fichier trouvé ici, voici l'écran que l'on peut voir :

![erreur_csv](https://cloud.githubusercontent.com/assets/7688741/18169363/197bc84a-705a-11e6-9dba-52d17e27f481.png)

Dans les logs 
```
2016-09-01 15:36:28.243996819 +0200 CEST [web-1] CSV::MalformedCSVError (Illegal quoting in line 2.):
2016-09-01 15:36:28.244205376 +0200 CEST [web-1]   app/controllers/transfert_csv_controller.rb:6:in `create'
```

**Comment by annemarie35** [comment]
@krichtof c'est le wiki qui m'a induit en erreur, j'ai téléchargé le premier fichier

**Comment by philcassagne** [comment]
Changer le csv sur le wiki ;)
