### ISSUE TITLE
En tant qu'opérateur, je peux transmettre le plan de financement et le plan de travaux à la DDT

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#55]
En tant qu'opérateur, je peux transmettre le plan de financement et le plan de travaux à la DDT. Un bouton est prévu. Actionner ce bouton génère un email (revoir wording). 
Les données plan de financement et plan de travaux doivent être visible dans l'espace instructeur, à créer.
Question : les données du plan de financement sont elles recueillies par API ?

**Comment by krichtof** [comment]
Les données du plan de financement sont effectivement reccueillies par API.
Le plan de travaux et le plan de financement sont accessibles lorsqu'un instructeur est connecté (pour l'instant, à l'aide du lien contenu dans le mail) sur la page demande.
