### ISSUE TITLE
En tant qu'opérateur et/ou instructeur, je peux me connecter via Clavis depuis la welcome page

### ISSUE THREAD

**Issue by annemarie35** [sgmap/mpal#69]
En tant qu'opérateur et/ou instructeur, depuis la home page,
J'ai un lien pour l'acces operateur/instructeur, 
Si je ne suis pas connecté, je suis redirigé vers la page de login qui contient un formulaire pour les demandeur et un pour l'authentification clavis
Si je suis connecté; ou une fois que je suis connecté; j'accède à la liste de mes projets

**Comment by krichtof** [comment]
En tant qu'opérateur et/ou instructeur, je peux me connecter via Clavis. Une fois connecté, j'arrive par défaut sur une page listant la liste des projets qui me sont assignés, ou la liste des projets qui sont visibles par la structure dans laquelle je travaille (opérateur, ddt, ...)
