### ISSUE TITLE
Ajouter lien vers site web des opérateurs

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#77]
On demandera aux opérateurs de fournir une adresse vers une page.
On pourrait prévoir le champ et faire un exemple d'affichage pour le département 25 
https://www.soliha.fr/ pour Soliha
http://www.julienne-javel.org/ pour Julienne Javel
http://www.urbam.fr/ pour Urbam Conseil

**Comment by annemarie35** [comment]
Rejoint la fonctionnalité plus complète #80
