### ISSUE TITLE
En tant que demandeur, à quelles données du traitement de mon dossier ai-je accès ?

### ISSUE THREAD

**Issue by annemarie35** [sgmap/mpal#79]
Par exemple, est-ce pertinent de savoir que je suis éligible ou de pouvoir refaire le calcul ? Ou bien considère-t-on que c'est une données surtout utile pour le traitement de la demande par les opérateurs et instructeurs

**Comment by krichtof** [comment]
L'idée générale est que tout le monde voit la même chose. Ensuite, certaines données peuvent être en écriture pour certains intervenants, et en lecture pour d'autres.
