### ISSUE TITLE
Franciser les dates

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#82]
Exemple : date  de naissance : 1979-05-06 lorsqu'on modifie le demandeur
http://anah-demo.beta.gouv.fr/projets/85/occupants/160/edition

**Comment by annemarie35** [comment]
Je vois bien le format français, tu es sur quel navigateur ?
![date_format](https://cloud.githubusercontent.com/assets/7688741/18272665/440eaf9a-7439-11e6-9e41-4feee09437e4.png)

**Comment by philcassagne** [comment]
Firefox 
![capture](https://cloud.githubusercontent.com/assets/19781930/18311472/d2eb6ade-7504-11e6-9794-9acd77180b21.JPG)
