### ISSUE TITLE
Améliore ou précise le calcul du revenu total du foyer en ajoutant le RFR d'un occupant

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#86]
Lorsqu'on ajoute un occupant, comment ajouter le RFR de cet occupant?
Les deux fonctions (ajout occupant et calcul RFR) sont dissociées et il faut ajouter des avis d'imposition avec 95 / 1595 par exemple, or cela correspond à deux occupants. N'a t on pas besoin de données de test supplémentaires ?

**Comment by annemarie35** [comment]
Pour le moment, il n'a pas été statué qu'un avis d'imposition devait être rattaché à un occupant. 
On ajoute simplement des avis d'impositions à un projet et on incrémente le revenu total avec les revenus de l'avis ajouté.  

Tu peux tester en ajoutant comme avis d'imposition ceux des autres départements disponibles.
Actuellement si l'avis d'imposition contient des occupants à charge et/ou deux déclarants, ces données ne sont pas reportées dans le calcul du nombre d'occupants. 
On peut également ajouter plusieurs fois de suite le même avis d'imposition. Et surement d'autres choses ne fonctionnent pas. 
Cette fonctionnalité n'est pas terminée, elle n'était pas prioritaire.

Et oui, on va devoir ajouter de nouveaux demandeurs, d'autant plus qu'on va avoir besoin de plusieurs dossiers par opérateurs.

**Comment by annemarie35** [comment]
@krichtof

**Comment by philcassagne** [comment]
Possible, mais je n'ai pas accédé à l'espace opérateur ce matin.

**Comment by annemarie35** [comment]
Vu en atelier wording le 17/10, cette fonctionnalité revient dans la liste des priorités

**Comment by annemarie35** [comment]
J'ajoute un occupant (année de naissance, avis d'imposition, etc.)
