### ISSUE TITLE
retour sur un projet existant - erreur

### ISSUE THREAD

**Issue by philcassagne** [sgmap/mpal#87]
Sans action Reset on obtient un message d'erreur après avoir ajouté un occupant ou ajouté un avis d'imposition (je ne sais pas ce qui provoque l'erreur)

**Comment by annemarie35** [comment]
Je n'arrive pas à reproduire le bug en local, je vais voir en ligne.
C'est à quel moment ? Quand on clique sur "J'ajoute un occupant" ?

**Comment by philcassagne** [comment]
Je crois que c'est après avoir ajouté un occupant ou un RFR.
Je tente aussi de le reproduire et reviens sur l'issue

**Comment by philcassagne** [comment]
Je n'arrive pas non plus à reproduire le pb en créant un occupant ou un rfr. Mettons de côté.

**Comment by annemarie35** [comment]
Ok, sachant que nous n'avons toujours pas résolu totalement le bug qui faisait qu'une fois connecté comme opérateur, on ne pouvait plus se connecter comme demandeur. C'est peut-être lié à ça.
@krichtof ça rejoint l'issue #75

**Comment by annemarie35** [comment]
C'est à priori réglé, je n'ai plus rencontré de bug. On réouvrira une issue si cela se reproduit.
