### ISSUE TITLE
En tant qu'intervenant j'ai accès à un tableau de bord qui me permet de piloter les projets.

### ISSUE THREAD

**Issue by annemarie35** [sgmap/mpal#90]
Propositions suite à l'open lab du 25 août : 

- Les données côté instructeurs et opérateurs sont les mêmes
- Les services instructeurs peuvent voir les dossiers en cours de montage chez les opérateurs

**Les informations en colonnes sont :**

- ID Plate-forme
- ID OPAL lorsque le dossier a été créé dans OPAL
- Nom et prénom du demandeur
- Adresse du logement objet de la demande
- Nature des travaux (à prévoir dans la fiche de synthèse), selon référentiel OPAL
- Type d'immeuble (à prévoir dans la fiche de synthèse), selon référentiel OPAL
- Nom du référent traitant le dossier : 
il s'agit côté opérateur, de la dernière personne ayant mis le dossier à jour 
il s'agit côté instructeur, de la personne ayant transmis le dossier à OPAL
- Etat du dossier

Avant transfert du dossier dans OPAL : position du dossier selon action de l'opérateur. 

**Etats proposés :**

_Version détaillée_
- Demande d'information
- Proposition
- Operateur missionné
- Visite programmée
- Diagnostic effectué
- Devis complet
- Transmis aux services instructeurs

_Version synthétique_

- Prospect (ou champ vide)
- En cours
- Transmis aux services instructeurs

Après création du dossier dans OPAL : position du dossier dans OPAL (les positions OPAL seront adaptées pour une meilleure compréhension du demandeur et des utilisateurs : voir en annexe la table de corespondance proposée)

L'intervenant peut accéder au détail d'un dossier

**Comment by krichtof** [comment]
Un nouvel état a été proposé en plus de prospect, en cours, et transmis aux services instructeurs.
Celui de "Abandonné"

**Comment by krichtof** [comment]
Qu'est-ce qui permet de passer de l'état "prospect" à l'état "En cours" ?

**Comment by philcassagne** [comment]
Supprimer les deux colonnes suivantes du tableau de bord, mais en effet les prévoir dans la  fiche de synthèse.
Nature des travaux (à prévoir dans la fiche de synthèse), selon référentiel OPAL
Type d'immeuble (à prévoir dans la fiche de synthèse), selon référentiel OPAL

Mais ajouter la colonne "Thématique" qui vient aussi de la fiche de synthèse

**Comment by krichtof** [comment]
La liste des projets est accessible.
A propos de la colonne thématique, voir #115
